import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "@/context/Providers";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "XHUFTS",
  description: "Generated by XHUFTS",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          {/* Navbar */}
          <div className="bg-zinc-900">
            <Navbar />
          </div>

          {/* Main Content */}
          <div className="flex-grow container mx-auto px-4 md:px-8 lg:px-12">
            {children}
          </div>

          {/* Footer 
          <div className="bg-zinc-900">
            <Footer />
          </div>
          */}
        </Providers>
      </body>
    </html>
  );
}
